const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { chromium } = require('playwright-core');
const { resolveConfig } = require('../server/config');
const { createApp } = require('../server/server');

test('тендер показывает матрицу и передаёт выбранный счёт в заказ', { timeout: 45_000 }, async (t) => {
  const rootDir = path.resolve(__dirname, '..');
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'klm-tender-'));
  const config = resolveConfig(rootDir);
  Object.assign(config, { dataDir, databaseFile: path.join(dataDir, 'klm.sqlite'), filesDir: path.join(dataDir, 'files'), importsDir: path.join(dataDir, 'imports'), backupsDir: path.join(dataDir, 'backups') });
  const server = createApp(config);
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  const browser = await chromium.launch({ executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true });
  t.after(async () => { await browser.close(); server.close(); });
  const page = await browser.newPage({ viewport: { width: 1800, height: 1100 } });
  page.setDefaultTimeout(7_000);
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await page.locator('#orderTab').click();
  await page.locator('#orderProjectFilter').click();
  await page.locator('#orderProjectOptions input').first().check();
  await page.locator('#orderProjectOk').click();
  await page.waitForSelector('#itemsBody .item-name');
  const item = await page.locator('#itemsBody tr').first().evaluate((row) => ({ name: row.querySelector('.item-name').value, unit: row.querySelector('.item-unit-value').textContent.trim(), quantity: row.querySelector('.item-quantity').value }));
  await page.locator('#itemsBody .item-selected').first().check();
  await page.waitForTimeout(500);
  await page.evaluate((item) => {
    const tender = JSON.parse(localStorage.getItem('klmProcurementTenderV1'));
    const order = JSON.parse(localStorage.getItem('klm-order-panel-standalone-v1'));
    const project = tender.groups[0].project;
    const lineId = 'test-invoice#L1';
    tender.manualLinks[lineId] = { project, requirementKey: tender.groups[0].requirementKey, quantity: Number(item.quantity), unit: item.unit, confirmed: true };
    localStorage.setItem('klmProcurementTenderV1', JSON.stringify(tender));
    localStorage.setItem('klmLocallyImportedInvoices', JSON.stringify([{ sourceFileKey: 'test-invoice', sourceFileName: 'Счёт ТЕСТ-001.pdf', invoice: 'Счёт № ТЕСТ-001', supplierInvoiceNumber: 'ТЕСТ-001', supplier: 'БЕЛПРОМСВЕТ ООО', payer: 'Главпроект', project, amount: 15000, invoiceLines: [{ id: lineId, name: item.name, unit: item.unit, quantity: Number(item.quantity), price: 1500, sum: 15000 }] }]));
    localStorage.setItem('klm-order-panel-standalone-v1', JSON.stringify(order));
  }, item);
  await page.reload();
  await page.waitForFunction(() => typeof window.klmRenderProcurementExtensions === 'function');
  await page.waitForTimeout(600);
  await page.locator('#tenderTab').click();
  await page.waitForSelector('.tender-comparison-matrix');
  const headers = await page.locator('.tender-comparison-matrix th').allTextContents();
  for (const expected of ['№п/п', 'НАИМЕНОВАНИЕ ТМЦ', 'ед.изм.', 'кол-во', 'БЕЛПРОМСВЕТ ООО', 'Цена', 'Сумма']) assert.ok(headers.some((value) => value.includes(expected)), `нет заголовка ${expected}`);
  assert.ok((await page.locator('.tender-total-row').innerText()).includes('15 000'));
  await page.locator('[data-tender-winner="БЕЛПРОМСВЕТ ООО"]').check();
  await page.locator('#orderTab').click();
  assert.equal(await page.locator('#order').inputValue(), 'ТЕСТ-001');
  assert.ok((await page.locator('#orderSupplierSummary').innerText()).includes('БЕЛПРОМСВЕТ ООО'));
});
